// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcvlzfshobiagunbnucg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjdmx6ZnNob2JpYWd1bmJudWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjUzMjYsImV4cCI6MjA2MjgwMTMyNn0.3I0Ru9Qglk_XVpgK9hrghuVYq9OpP4oaJaGQQ721QIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);